### ISSUE TITLE
Feature: push multiple lines of output to terminal without triggering prompt

### ISSUE THREAD

**Issue by JoshuaBThompson** [ndabAP/vue-command#215]
I have a situation where I need to display some instructions to a user on the terminal, for example, after some timeout where user does not enter anything into the prompt.
What I want to do is something like:
- user has not entered anything after 10 seconds
- after 10 seconds is up some instructions are displayed 1 second apart
```bash
>> 
COUNT DOWN TILL PROGRAM QUITS....
ONE (happens 1 second after prev line)
TWO (happens 1 second after prev line)
THREE (happens 1 second after prev line)
```

I can't figure out how to do something like this - how to push multiple lines of output separately. 
- Currently, when I push a line of output using:
   + this.history.push(createStdout('hello'))
   + the terminal inserts a prompt right after (this is what I want to disable)

- For example if I do:
   + this.history.push(createStdout('hello'))
   + this.history.push(createStdout('world'))
- then I see
```bash
hello
>>
world
>>
```

- instead of
```bash
hello
world
```

**Comment by ndabAP** [comment]
Every `Stdout` is followed by a prompt (in this library for abstraction purposes `Stdin`). But you can always return your own component and do what you want inside. This component from the demo, for example, is not created with the `createStdout` helper method: https://github.com/ndabAP/vue-command/blob/master/src/hosted/LoadingAnimation.vue

**Comment by JoshuaBThompson** [comment]
@ndabAP thanks for the reference. I was hoping to continue using the createStdout for this. Looking at the code in VueCommand.vue it looks like there might be a straight forward way to add this as a feature to the stdout component so that the developer can decide to include a prompt or not after createStdout is called.
I made a PR for this: https://github.com/ndabAP/vue-command/pull/216
It works great for me so far but maybe I'm missing something. What do you think?

**Comment by Hextar** [comment]
@JoshuaBThompson Hello, I've come to this issue cause I'm trying to achieve the same result.

This is mainly because I've implemented the frontend to pass the commands to the backend throught a websocket, and my desired behaviour is that I add a new line to the vue-command only when the websocket send a dedicated message, which is different approach from just hiding the prompt while is-in-progress equals true.

I see whe createStdout and createStderr append each time a **term-hist** div with both stdin and stdout, and I've tried to implement a custom content passing data to it using provide/inject but even after adding that component to the history, but then the stdin still appears
