### ISSUE TITLE
Feature: Have you considered using vuex for a store of many things rather than provide API and injection?

### ISSUE THREAD

**Issue by shaenr** [ndabAP/vue-command#229]
Not sure if its always better to do that or not.

**Comment by ndabAP** [comment]
Hey @shanerowden,

yeah, it was [open issue](https://github.com/ndabAP/vue-command/issues/113) but I closed because of inactivity. 

Vuex can be a good addition, absolutely. I wanted to wait for Vue.js 3 and the changing concepts of Vuex (if any) before I or someone has to rewrite the Vuex bindings again. There were no serious plans if it makes more sense or not, yet.
