### ISSUE TITLE
Feature: Execute command programmatically from outside

### ISSUE THREAD

**Issue by Baloneo** [ndabAP/vue-command#257]
Will consider adding this feature?

**Comment by Arun4rangan** [comment]
I would like to take this ticket on!  I want to have similar functionality, i want to programmatically change the history inside the vue-command.  

The idea I had:

Since stdin is depended on `local.stdin` , we could move that into history props.  History props would have both stdin and the resulting stdout component.  Then when we `v-for="({stdout, stdin}, index) in local.history"` in `VueCommand`, we could point `stdin.sync` to either `stdin || local.stdin`.

This way if anyone wants to execute comment programmatically from the outside, they just need to add it to history props.

Let me know if you agree with this?

**Comment by ndabAP** [comment]
That's now possible. Use the exposed function `dispatch(command)`.
